apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goframe-operator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "goframe-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "goframe-operator.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "goframe-operator.name" . }}
    spec:
      serviceAccountName: {{ include "goframe-operator.name" . }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --health-probe-bind-address=:8083
            - --metrics-bind-address=:8082
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect
            {{- end }}
          ports:
            - name: metrics
              containerPort: 8082
              protocol: TCP
            - name: health
              containerPort: 8083
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
