apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goframe-operator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "goframe-operator.labels" . | nindent 4 }}
