port: 8080
connectionString: "someconnectionstring"
imageTargetType: "png"
commands:
  - name: OrientationCommand
    orientation: portrait
  - name: ScaleCommand
    height: 1920
    width: 1080
  - name: CropCommand
    height: 1600
    width: 1200
  - name: Spectra6DitheringCommand