apiVersion: v2
name: goframe-operator
description: Helm chart for the GoFrame Kubernetes operator (install once per cluster)
type: application
version: 4.0.6
appVersion: "4.0.1"
keywords:
  - go
  - operator
  - kubernetes
sources:
  - https://github.com/jo-hoe/goframe
