# Local k3d development overrides
# Applied to: helm upgrade --install goframe charts/goframe
timezone: "UTC"

server:
  image:
    repository: registry.localhost:5000/goframe
    tag: latest
    pullPolicy: Always
  port: 8080
  thumbnailWidth: 512
  logLevel: "info"
  svgFallbackLongSidePixelCount: 4096

commands:
  - name: RotationCommand
    steps: 1         # 1=90°, 2=180°, 3=270°
    clockwise: true  # optional, default: true

schedulers:
  - name: xkcd
    cron: "*/1 * * * *"
    source: xkcd
    keepCount: 1
    image:
      repository: registry.localhost:5000/goframe-image-scheduler
      tag: latest
      pullPolicy: Always
  - name: pusheen
    cron: "*/1 * * * *"
    source: pusheen
    keepCount: 1
    drainIfUnmanagedImagesExceed: 1
    image:
      repository: registry.localhost:5000/goframe-image-scheduler
      tag: latest
      pullPolicy: Always

  - name: oatmeal
    cron: "*/1 * * * *"
    source: oatmeal
    keepCount: 1
    drainIfUnmanagedImagesExceed: 2
    image:
      repository: registry.localhost:5000/goframe-image-scheduler
      tag: latest
      pullPolicy: Always

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
