apiVersion: v2
name: goframe
description: Helm chart for the goframe image processing web service
type: application
version: 12.0.5
appVersion: "12.0.5"
keywords:
  - go
  - image
  - web
sources:
  - https://github.com/jo-hoe/goframe
