apiVersion: goframe.io/v1alpha1
kind: GoFrame
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  timezone: {{ .Values.timezone | quote }}

  redis:
    {{- if .Values.redis.address }}
    address: {{ .Values.redis.address | quote }}
    {{- else }}
    address: {{ printf "redis-master.%s.svc.cluster.local:6379" .Release.Namespace | quote }}
    {{- end }}

  server:
    image:
      repository: {{ .Values.server.image.repository | quote }}
      tag: {{ .Values.server.image.tag | default .Chart.AppVersion | quote }}
      pullPolicy: {{ .Values.server.image.pullPolicy | quote }}
    port: {{ .Values.server.port }}
    thumbnailWidth: {{ .Values.server.thumbnailWidth }}
    logLevel: {{ .Values.server.logLevel | quote }}
    svgFallbackLongSidePixelCount: {{ .Values.server.svgFallbackLongSidePixelCount }}
    serviceType: {{ .Values.server.serviceType | quote }}

  {{- if .Values.commands }}
  commands:
    {{- range .Values.commands }}
    - name: {{ .name | quote }}
      {{- $params := omit . "name" }}
      {{- if $params }}
      params: {{ $params | toJson }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- if .Values.schedulers }}
  schedulers:
    {{- range .Values.schedulers }}
    - name: {{ .name | quote }}
      cron: {{ .cron | quote }}
      source: {{ .source | quote }}
      {{- if .keepCount }}
      keepCount: {{ .keepCount }}
      {{- end }}
      {{- if .exclusionGroup }}
      exclusionGroup: {{ .exclusionGroup | quote }}
      {{- end }}
      {{- if .query }}
      query: {{ .query | quote }}
      {{- end }}
      {{- if .departmentIDs }}
      departmentIDs:
        {{- range .departmentIDs }}
        - {{ . }}
        {{- end }}
      {{- end }}
      {{- if .blog }}
      blog: {{ .blog | quote }}
      {{- end }}
      {{- if .commands }}
      commands:
        {{- range .commands }}
        - name: {{ .name | quote }}
          {{- $params := omit . "name" }}
          {{- if $params }}
          params: {{ $params | toJson }}
          {{- end }}
        {{- end }}
      {{- end }}
      image:
        repository: {{ ((.image).repository) | default $.Values.schedulerImage.repository | quote }}
        tag: {{ ((.image).tag) | default $.Chart.AppVersion | quote }}
        pullPolicy: {{ ((.image).pullPolicy) | default $.Values.schedulerImage.pullPolicy | quote }}
    {{- end }}
  {{- end }}
