{{- range .Values.schedulers }}
{{- if and .s3 .s3.accessKey .s3.secretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-sched-%s-s3-credentials" $.Release.Name .name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "goframe.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  accessKey: {{ .s3.accessKey | quote }}
  secretKey: {{ .s3.secretKey | quote }}
{{- end }}
{{- end }}
