{{- if .Values.seaweedfs.ingress.enabled }}
{{- $bucket := .Values.seaweedfs.bucket | default .Release.Name }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-seaweedfs-rewrite
  namespace: {{ .Release.Namespace }}
spec:
  replacePathRegex:
    regex: "^/images/(.*)"
    replacement: "/{{ $bucket }}/images/$1"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-seaweedfs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ .Release.Name }}-seaweedfs-rewrite@kubernetescrd
    {{- with .Values.seaweedfs.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- $seaweedfsClass := .Values.seaweedfs.ingress.className | default .Values.ingress.className }}
  {{- if $seaweedfsClass }}
  ingressClassName: {{ $seaweedfsClass }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - {{- if .host }}
      host: {{ .host | quote }}
      {{- end }}
      http:
        paths:
          - path: /images
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-seaweedfs
                port:
                  number: 9000
    {{- end }}
{{- end }}
