apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-seaweedfs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: s3
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/instance: {{ .Release.Name }}
